// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhoneSite.Data;

namespace PhoneSite.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191202152111_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhoneSite.Models.FirmPhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageFirm");

                    b.Property<string>("NameFirm");

                    b.HasKey("Id");

                    b.ToTable("FirmPhones");
                });

            modelBuilder.Entity("PhoneSite.Models.ImagePhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageModelAddress");

                    b.Property<int>("ModelPhoneId");

                    b.Property<bool>("isMain");

                    b.HasKey("Id");

                    b.HasIndex("ModelPhoneId");

                    b.ToTable("ImagePhones");
                });

            modelBuilder.Entity("PhoneSite.Models.ModelPhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Battery");

                    b.Property<string>("Camera");

                    b.Property<string>("Display");

                    b.Property<int>("FirmPhoneId");

                    b.Property<string>("Model");

                    b.Property<string>("Others");

                    b.Property<string>("Price");

                    b.Property<string>("Processor");

                    b.Property<string>("Storage");

                    b.HasKey("Id");

                    b.HasIndex("FirmPhoneId");

                    b.ToTable("ModelPhones");
                });

            modelBuilder.Entity("PhoneSite.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhoneSite.Models.ImagePhone", b =>
                {
                    b.HasOne("PhoneSite.Models.ModelPhone", "ModelPhone")
                        .WithMany("ImagePhones")
                        .HasForeignKey("ModelPhoneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PhoneSite.Models.ModelPhone", b =>
                {
                    b.HasOne("PhoneSite.Models.FirmPhone", "FirmPhone")
                        .WithMany("ModelPhones")
                        .HasForeignKey("FirmPhoneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
